### PR TITLE
Update DefaultInterestRateStrategy of v2 with v3 interface

### PR DESCRIPTION
**Pull request by kyzia551**

### CODE REVIEW

**Comment by eboadom** [comment]
For what is exactly this contract? https://github.com/bgd-labs/protocol-v2/blob/34f8926a7e0aa8fcf9c4876fc69a44fa02ec895d/contracts/misc/UiPoolDataProviderV2V3.sol

**Comment by kyzia551** [comment]
@sakulstra @sendra

**Review by sakulstra — COMMENTED** [review]
Looking good to me, but i'm wondering if it would make sense to keep the old methods as well to don't break compatibilities.
A agree that having them is kinda weird as well. Not sure why things were changed in the first place.

**Comment by kyzia551** [comment]
not applicable

**Pull request closed without merging**
